# ----------------------- #
#      Main Configs       #
# ----------------------- #

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

url: "http://localhost"
port: 4004
title: Make Technology
name: Make Technology
email: seba.sampaoli@gmail.com
author: Sebastian Sampaoli
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

author:
  name: Sebastian Sampaoli
  email: seba.sampaoli@gmail.com
  github: ssampaoli
  twitter: sebasampaoli
  feedburner: feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://ssampaoli.github.io
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: linkedin
    url: 

blog_path: /blog.html
# blog_path : /posts.html

